-- Requires the existing bronze_ingest_batch table.
-- CREATE TABLE IF NOT EXISTS does not migrate an existing table.
CREATE TABLE IF NOT EXISTS bronze_cate_info (
    seq_num INT NOT NULL,
    q_type INT NOT NULL COMMENT '카테고리 코드',
    q_disp_name VARCHAR(255) NOT NULL COMMENT '화면 표시명',
    state TINYINT NOT NULL COMMENT '사용 상태 (0/1 확인 필요)',
    regdate BIGINT NOT NULL COMMENT '등록일시 epoch',
    _ingest_batch_id VARCHAR(36) NOT NULL,
    _ingested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _source_table VARCHAR(100) NOT NULL DEFAULT 'cate_info',
    _source_file VARCHAR(255) NULL,
    _row_hash VARCHAR(64) NOT NULL COMMENT '중복 적재 방지용 행 해시',
    PRIMARY KEY (_ingest_batch_id, seq_num),
    CONSTRAINT fk_cate_info_batch FOREIGN KEY (_ingest_batch_id)
        REFERENCES bronze_ingest_batch(ingest_batch_id)
);

CREATE TABLE IF NOT EXISTS bronze_counselling_info (
    seq_num INT NOT NULL,
    id_name VARCHAR(50) NULL,
    q_type INT NULL COMMENT '카테고리 코드',
    ci_status INT NULL COMMENT '상태값 (확인 필요)',
    ci_type INT NULL COMMENT '유형 (확인 필요)',
    ci_question TEXT NULL COMMENT '대표 질문 문구',
    ci_disp_name TEXT NULL COMMENT '표시 질문명',
    ci_depth1_id VARCHAR(50) NULL,
    ci_depth2_id VARCHAR(50) NULL,
    ci_depth3_id VARCHAR(50) NULL,
    ci_depth4_id VARCHAR(20) NULL,
    ci_session1_id VARCHAR(50) NULL,
    ci_session2_id VARCHAR(50) NULL,
    ci_session3_id VARCHAR(50) NULL,
    ci_session4_id VARCHAR(50) NULL,
    disp_link1 VARCHAR(255) NULL,
    disp_link2 VARCHAR(255) NULL,
    disp_link3 VARCHAR(255) NULL,
    disp_link4 VARCHAR(255) NULL,
    disp_link5 VARCHAR(255) NULL,
    link1 TEXT NULL,
    link2 TEXT NULL,
    link3 TEXT NULL,
    link4 TEXT NULL,
    link5 TEXT NULL,
    link1_msg TEXT NULL,
    link2_msg TEXT NULL,
    link3_msg TEXT NULL,
    link4_msg TEXT NULL,
    link5_msg TEXT NULL,
    ci_answer0 LONGTEXT NULL COMMENT '기본 답변 본문',
    more_txt TEXT NULL,
    more_contents TEXT NULL,
    img_file1 TEXT NULL,
    ci_reg_date BIGINT NULL,
    ci_mod_date BIGINT NULL,
    ci_ans_sre TEXT NULL,
    ci_ans_sre_keyword TEXT NULL,
    state TINYINT NULL,
    qa_cnt INT NOT NULL DEFAULT 0 COMMENT '누적 질의 수',
    recent_qa BIGINT NULL,
    reg_year INT NULL,
    _ingest_batch_id VARCHAR(36) NOT NULL,
    _ingested_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    _source_table VARCHAR(100) NOT NULL DEFAULT 'counselling_info',
    _source_file VARCHAR(255) NULL,
    _row_hash VARCHAR(64) NOT NULL,
    PRIMARY KEY (_ingest_batch_id, seq_num),
    CONSTRAINT fk_counselling_info_batch FOREIGN KEY (_ingest_batch_id)
        REFERENCES bronze_ingest_batch(ingest_batch_id)
);
